name: Convert MP4 with Subtitle and Upload to Google Drive

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libass-dev
          python3 -m pip install --upgrade pip
          python3 -m pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Create token.pickle
        run: |
          echo "${{ secrets.GDRIVE_TOKEN }}" | base64 --decode > token.pickle

      - name: Download Subtitle file
        run: |
          curl -L -o subtitle.srt "https://str.tipiku.my.id/hardsub/series/stone/stone6.srt"
          ls -lah $(pwd)

      - name: Check Subtitle Existence
        run: |
          if [ ! -f $(pwd)/subtitle.srt ]; then
            echo "Error: subtitle.srt not found!"
            exit 1
          fi

      - name: Download Video file
        run: |
          curl -L -o video.mp4 "https://tipistream.tipikuy.workers.dev/0:/series/anime/drstone4/stone6.mp4"
          ls -lah $(pwd)

      - name: Check Video Existence
        run: |
          if [ ! -f $(pwd)/video.mp4 ]; then
            echo "Error: video.mp4 not found!"
            exit 1
          fi

      - name: Burn subtitles into MP4 (Hardsub)
        run: |
          ffmpeg -i video.mp4 -vf "subtitles=subtitle.srt" -c:a copy output.mp4

      - name: Upload to Google Drive
        run: python3 upload_to_gdrive.py output.mp4
