name: Convert MP4 with Subtitle and Upload to Google Drive

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        python3 -m pip install --upgrade pip
        python3 -m pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Create credentials.json
      run: |
        echo "${{ secrets.GDRIVE_TOKEN }}" | base64 --decode > credentials.json

    - name: Download MP4 file
      run: |
        curl -L -o video.mp4 "https://tipistream.tipikuy.workers.dev/0:/series/anime/drstone4/stone8.mp4"

    - name: List files for debugging
      run: ls -lh


    - name: Burn subtitles into MP4 (Hardsub)
      run: |
        ffmpeg -i video.mp4 -vf "subtitles=subtitle.srt" -c:a copy output.mp4

    - name: Verify output file
      run: ls -lh output.mp4

    - name: Upload to Google Drive
      run: python3 upload_to_gdrive.py output.mp4
